# Verifies building

on:
  push:
  pull_request:
    branches:
      - master
    types:
      - opened
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
          submodules: True

      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: bullseye
          githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
            -u root

          install: |
            apt-get update
            apt-get install -y build-essential pkg-config gcc g++ python3 python3-pip cmake libgl-dev libxcb-util-dev libx11-xcb-dev
            python3 -m pip install conan==1.63.0 cantools

          run: |
            conan remote add grc ${{ secrets.CONAN_REMOTE_URL }} --force
            conan remove "*" -f
            conan install software -if build -pr:h software/ConanProfiles/pi4b-Release.ini -pr:b software/ConanProfiles/pi4b-Release.ini -r grc -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True
            conan build software -if build
            cp -r software/build/Release/bin /artifacts

      # - name: Build deploy bundle
      #   run: |
      #       wget -c -nv "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage"
      #       wget -c -nv "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
      #       chmod a+x linuxdeploy-plugin-qt-x86_64.AppImage
      #       chmod a+x linuxdeploy-x86_64.AppImage
      #       export QML_SOURCES_PATHS=./src/Dash

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: RPI1.2b+DashFront-Release
          path: artifacts
