# Checks Formatting (clang-format)

on:
  push:
  pull_request:
    branches:
      - master
    types:
      - opened
      - closed

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check C/C++ files
        if: always()
        uses: DoozyX/clang-format-lint-action@v0.15
        with:
          source: './src'
          extensions: 'h,hpp,cpp,c'
          clangFormatVersion: 12
          style: file

      - name: Check CMake files
        # Always run formatter so user gets the most information possible
        if: always()
        run: |
          python -m pip install cmakelang[YAML]
          # cmake-format has a funky issue, where when --check is set, and it takes in multiple files, the extra configuration parameters don't affect the result
          # We have forced a single file per command with xargs -n 1
          find . \( -name '*.cmake' -o -name 'CMakeLists.txt' \) | xargs -n 1 cmake-format --check
